"""
Agent Team 导出服务
P1阶段：将团队配置导出为Agno兼容的Python代码
"""

from typing import List
from sqlalchemy.orm import Session

from ..models_db import Agent, AgentTeam, AgentTeamNode, AgentTeamEdge


def export_team_as_python(
    team: AgentTeam,
    nodes: List[AgentTeamNode],
    edges: List[AgentTeamEdge],
    db: Session
) -> str:
    """
    将团队配置导出为Agno兼容的Python代码
    """
    # 获取所有Agent配置
    agent_ids = [node.agent_id for node in nodes]
    agents = db.query(Agent).filter(Agent.id.in_(agent_ids)).all()
    agent_map = {str(agent.id): agent for agent in agents}

    # 生成代码
    code_lines = [
        '"""',
        f'{team.name} - Agent Team Configuration',
        f'Generated by AgentNex Platform',
        f'Goal: {team.goal}',
        '"""',
        '',
        'from agno import Agent, Team',
        'from agno.models import Qwen',
        '',
        '',
    ]

    # 生成Agent定义
    for node in nodes:
        agent = agent_map.get(str(node.agent_id))
        if not agent:
            continue

        agent_var = _sanitize_name(agent.name)

        code_lines.extend([
            f'# {agent.name}',
            f'{agent_var} = Agent(',
            f'    name="{agent.name}",',
            f'    model=Qwen(id="{agent.model_id}"),',
        ])

        if agent.system_prompt:
            prompt_lines = agent.system_prompt.split('\n')
            if len(prompt_lines) == 1:
                code_lines.append(f'    instructions="{agent.system_prompt}",')
            else:
                code_lines.append('    instructions="""')
                for line in prompt_lines:
                    code_lines.append(f'        {line}')
                code_lines.append('    """,')

        if agent.temperature != 70:
            code_lines.append(f'    temperature={agent.temperature / 100},')

        # 添加角色信息
        if node.role_in_team:
            code_lines.append(f'    role="{node.role_in_team}",')

        code_lines.extend([
            ')',
            '',
        ])

    # 生成Team定义
    team_var = _sanitize_name(team.name) + "_team"
    agent_vars = [_sanitize_name(agent_map[str(node.agent_id)].name) 
                  for node in nodes if str(node.agent_id) in agent_map]

    code_lines.extend([
        f'# Team: {team.name}',
        f'{team_var} = Team(',
        f'    name="{team.name}",',
        f'    agents=[{", ".join(agent_vars)}],',
    ])

    if team.global_prompt:
        code_lines.append(f'    instructions="{team.global_prompt}",')

    code_lines.extend([
        f'    mode="{team.communication_mode.value}",',
        f'    max_rounds={team.max_rounds},',
        ')',
        '',
        '',
    ])

    # 生成运行示例
    code_lines.extend([
        '# Run the team',
        'if __name__ == "__main__":',
        f'    result = {team_var}.run("Your task here")',
        '    print(result)',
        '',
    ])

    return '\n'.join(code_lines)


def _sanitize_name(name: str) -> str:
    """
    将名称转换为合法的Python变量名
    """
    # 替换空格和特殊字符
    sanitized = name.lower()
    sanitized = sanitized.replace(' ', '_')
    sanitized = sanitized.replace('-', '_')
    sanitized = ''.join(c for c in sanitized if c.isalnum() or c == '_')

    # 确保不以数字开头
    if sanitized and sanitized[0].isdigit():
        sanitized = 'agent_' + sanitized

    return sanitized or 'agent'
